### PR TITLE
📝 updated shard key singlestore documentation link

### PR DESCRIPTION
**Pull request by DanielFerguson**
The original link doesn't seem to work for me, so I'm suggesting to change to this link.

### CODE REVIEW

**Comment by aarondfrancis** [comment]
Ah good catch! Are the rest of the changes some sort of auto formatter? Looks like it caught a few double spaces.

**Comment by DanielFerguson** [comment]
It looks like it! I've got my VS Code setup to be pretty opinionated... 😅 I can revert, update the link and leave the rest of the formatting?

**Comment by aarondfrancis** [comment]
Yeah maybe just update the link? I dunno if it really matters, but it's probably cleaner that way!

**Comment by DanielFerguson** [comment]
Ok, let me know if that's better - I reverted back to the original document, updated the link and saved without executing my formatter.

**Comment by aarondfrancis** [comment]
Merged. Thanks @DanielFerguson!

**Pull request merged**
