### PR TITLE
Add withoutPrimaryKey method for increment columns

### LINKED ISSUE #22: Can't define custom primary key for my shard key with autoIncrement id
From reading the title, it may seem confusing. But here is the table example:

```php
Schema::create('referral_commissions', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->foreignId('user_id')->shardKey();
    $table->foreignId('referral_id')->index();
    $table->integer('amount');
    $table->timestamp('created_at')->nullable();

    // Indexes
    $table->primary(['id', 'user_id']);
});
```

I'm actually trying to create this table with `user_id` as the shard key. According to SingleStore documentation, the shard key is a subset of the primary key. Taking this into consideration, I set the primary key as `id, user_id`.

But that does not work since Laravel always sets the increment value as the primary key. This migration is trying to create a table with two primary keys, leading to this SingleStore error:

```
General error: 1851 COLUMNAR indexes and SKIPLIST indexes cannot be used on the same table
```

Generated code:
```
CREATE TABLE
  `referral_commissions` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` bigint unsigned NOT NULL,
    `referral_id` bigint unsigned NOT NULL,
    `amount` int NOT NULL,
    `created_at` TIMESTAMP NULL,
    PRIMARY KEY `referral_commissions_id_user_id_primary` (`id`, `user_id`),
    INDEX `referral_commissions_referral_id_index` (`referral_id`),
    shard key (`user_id`)
  ) DEFAULT CHARACTER
SET
  utf8mb4 COLLATE 'utf8mb4_unicode_ci'
```

This problem does not seem to be related to the driver but to Laravel itself, which always sets the increment as the primary key. But I think it will be very hard to change this in the framework.

Maybe the SingleStore driver could prevent or control this kind of behavior.

### PR DESCRIPTION
**Pull request by srdante**
Fixes #22 implementing the `withoutPrimaryKey` method:

```php
$table->bigIncrements('id')->withoutPrimaryKey();
```

### CODE REVIEW

**Comment by carlsverre** [comment]
Oops, left comment on #22 rather than here. Copying here for completeness:

I'm not a big fan of negating implicit behavior. What do you think about making bigIncrements not automatically make the auto_increment the primary key, and instead always requiring that the user declares the primary key on the table?

I.e. just making
```php
protected function modifyIncrement(Blueprint $blueprint, Fluent $column)
    {
        if (in_array($column->type, $this->serials) && $column->autoIncrement) {
            return 'auto_increment';
        }
    }
}

**Comment by srdante** [comment]
@carlsverre I also do not like the negating implicit behavior, but I think that changing the Laravel default behavior is not a good decision.

It would introduce a breaking change to everyone who is already using the library (forcing you to release 2.0.0 because of the semantic versioning) and would make the newcomers confused without a really big warning in the README.

Maybe a better name would be `notPrimary` if the `withoutPrimaryKey` doesn't sounds well:

```php
$table->id()->notPrimary();
```

**Comment by carlsverre** [comment]
Good points. Ok, I think this is good to go as is. I like `withoutPrimaryKey` better than `notPrimary`.

Separately, it seems that the tests are failing due to an issue with either the docker image or github service container healthchecks. Will investigate.

**Comment by carlsverre** [comment]
Ah, the issue is related to github not sharing the singlestore license secret with pull requests. I'll have to find another way to run actions on PR's. Very tricky.

**Comment by carlsverre** [comment]
Can you rebase on 6f0e84cb834dae2dac0824b4d21b0370107a5cbe. That will allow us to run tests on PRs.

**Pull request merged**
